<?php

use \Drupal\block_content\BlockContentInterface;

/**
 * @param array $attachments
 */
function bbelements_page_attachments(array &$attachments)
{
    $attachments['#attached']['library'][] = 'bbelements/external';
    $attachments['#attached']['library'][] = 'bbelements/own';
}


/**
 * Brings naming convention: block--block-content-{{ machine-name  }}.html.twig
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function bbelements_theme_suggestions_block_alter(array &$suggestions, array $variables) {
    $content = $variables['elements']['content'];
    if (isset($content['#block_content']) && $content['#block_content'] instanceof BlockContentInterface) {
        $suggestions[] = 'block__block_content_' . $content['#block_content']->bundle();
    }
}